// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DeliveryType string

const (
	DeliveryTypeDELIVERY DeliveryType = "DELIVERY"
	DeliveryTypePICKUP   DeliveryType = "PICKUP"
)

func (e *DeliveryType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeliveryType(s)
	case string:
		*e = DeliveryType(s)
	default:
		return fmt.Errorf("unsupported scan type for DeliveryType: %T", src)
	}
	return nil
}

type NullDeliveryType struct {
	DeliveryType DeliveryType `json:"delivery_type"`
	Valid        bool         `json:"valid"` // Valid is true if DeliveryType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeliveryType) Scan(value interface{}) error {
	if value == nil {
		ns.DeliveryType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeliveryType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeliveryType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeliveryType), nil
}

type DiscountType string

const (
	DiscountTypePERCENT DiscountType = "PERCENT"
	DiscountTypeFIXED   DiscountType = "FIXED"
)

func (e *DiscountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DiscountType(s)
	case string:
		*e = DiscountType(s)
	default:
		return fmt.Errorf("unsupported scan type for DiscountType: %T", src)
	}
	return nil
}

type NullDiscountType struct {
	DiscountType DiscountType `json:"discount_type"`
	Valid        bool         `json:"valid"` // Valid is true if DiscountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDiscountType) Scan(value interface{}) error {
	if value == nil {
		ns.DiscountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DiscountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDiscountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DiscountType), nil
}

type OrderStatus string

const (
	OrderStatusPENDING    OrderStatus = "PENDING"
	OrderStatusPAID       OrderStatus = "PAID"
	OrderStatusPROCESSING OrderStatus = "PROCESSING"
	OrderStatusSHIPPED    OrderStatus = "SHIPPED"
	OrderStatusDELIVERED  OrderStatus = "DELIVERED"
	OrderStatusCANCELLED  OrderStatus = "CANCELLED"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus `json:"order_status"`
	Valid       bool        `json:"valid"` // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type TransactionStatus string

const (
	TransactionStatusPENDING  TransactionStatus = "PENDING"
	TransactionStatusSUCCESS  TransactionStatus = "SUCCESS"
	TransactionStatusFAILED   TransactionStatus = "FAILED"
	TransactionStatusREFUNDED TransactionStatus = "REFUNDED"
)

func (e *TransactionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionStatus(s)
	case string:
		*e = TransactionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionStatus: %T", src)
	}
	return nil
}

type NullTransactionStatus struct {
	TransactionStatus TransactionStatus `json:"transaction_status"`
	Valid             bool              `json:"valid"` // Valid is true if TransactionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionStatus), nil
}

type UserRole string

const (
	UserRoleCUSTOMER UserRole = "CUSTOMER"
	UserRoleADMIN    UserRole = "ADMIN"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type CartItem struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	SkuID     uuid.UUID `json:"sku_id"`
	Quantity  int32     `json:"quantity"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Category struct {
	ID        uuid.UUID   `json:"id"`
	ParentID  pgtype.UUID `json:"parent_id"`
	Name      string      `json:"name"`
	Slug      string      `json:"slug"`
	CreatedAt time.Time   `json:"created_at"`
}

type Order struct {
	ID              uuid.UUID    `json:"id"`
	PublicNumber    string       `json:"public_number"`
	SearchIndex     pgtype.Text  `json:"search_index"`
	UserID          uuid.UUID    `json:"user_id"`
	Status          OrderStatus  `json:"status"`
	DeliveryType    DeliveryType `json:"delivery_type"`
	DeliveryAddress pgtype.Text  `json:"delivery_address"`
	PickupPointID   pgtype.UUID  `json:"pickup_point_id"`
	PromoCodeID     pgtype.UUID  `json:"promo_code_id"`
	TotalAmount     int32        `json:"total_amount"`
	DiscountAmount  int32        `json:"discount_amount"`
	CreatedAt       time.Time    `json:"created_at"`
	UpdatedAt       time.Time    `json:"updated_at"`
}

type OrderItem struct {
	ID              uuid.UUID `json:"id"`
	OrderID         uuid.UUID `json:"order_id"`
	SkuID           uuid.UUID `json:"sku_id"`
	Quantity        int32     `json:"quantity"`
	PriceAtPurchase int32     `json:"price_at_purchase"`
	CreatedAt       time.Time `json:"created_at"`
}

type PickupPoint struct {
	ID           uuid.UUID   `json:"id"`
	Name         string      `json:"name"`
	Address      string      `json:"address"`
	WorkingHours pgtype.Text `json:"working_hours"`
	IsActive     bool        `json:"is_active"`
	CreatedAt    time.Time   `json:"created_at"`
}

type Product struct {
	ID          uuid.UUID          `json:"id"`
	CategoryID  uuid.UUID          `json:"category_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

type PromoCode struct {
	ID            uuid.UUID          `json:"id"`
	Code          string             `json:"code"`
	DiscountType  DiscountType       `json:"discount_type"`
	DiscountValue int32              `json:"discount_value"`
	ValidUntil    pgtype.Timestamptz `json:"valid_until"`
	UsageLimit    pgtype.Int4        `json:"usage_limit"`
	UsedCount     int32              `json:"used_count"`
	CreatedAt     time.Time          `json:"created_at"`
}

type Session struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Sku struct {
	ID         uuid.UUID          `json:"id"`
	ProductID  uuid.UUID          `json:"product_id"`
	SkuCode    string             `json:"sku_code"`
	Attributes []byte             `json:"attributes"`
	Price      int32              `json:"price"`
	Stock      int32              `json:"stock"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt  time.Time          `json:"created_at"`
	UpdatedAt  time.Time          `json:"updated_at"`
}

type Transaction struct {
	ID                    uuid.UUID         `json:"id"`
	OrderID               uuid.UUID         `json:"order_id"`
	PaymentMethod         pgtype.Text       `json:"payment_method"`
	Status                TransactionStatus `json:"status"`
	Amount                int32             `json:"amount"`
	ProviderTransactionID pgtype.Text       `json:"provider_transaction_id"`
	CreatedAt             time.Time         `json:"created_at"`
	UpdatedAt             time.Time         `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         UserRole  `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
