// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addToCart = `-- name: AddToCart :one
INSERT INTO cart_items (user_id, sku_id, quantity)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, sku_id) 
DO UPDATE SET quantity = cart_items.quantity + EXCLUDED.quantity, updated_at = NOW()
RETURNING id, user_id, sku_id, quantity, created_at, updated_at
`

type AddToCartParams struct {
	UserID   uuid.UUID `json:"user_id"`
	SkuID    uuid.UUID `json:"sku_id"`
	Quantity int32     `json:"quantity"`
}

func (q *Queries) AddToCart(ctx context.Context, arg AddToCartParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, addToCart, arg.UserID, arg.SkuID, arg.Quantity)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SkuID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const clearCart = `-- name: ClearCart :exec
DELETE FROM cart_items WHERE user_id = $1
`

func (q *Queries) ClearCart(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearCart, userID)
	return err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    public_number, user_id, delivery_type, delivery_address, 
    pickup_point_id, total_amount, promo_code_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, public_number, search_index, user_id, status, delivery_type, delivery_address, pickup_point_id, promo_code_id, total_amount, discount_amount, created_at, updated_at
`

type CreateOrderParams struct {
	PublicNumber    string       `json:"public_number"`
	UserID          uuid.UUID    `json:"user_id"`
	DeliveryType    DeliveryType `json:"delivery_type"`
	DeliveryAddress pgtype.Text  `json:"delivery_address"`
	PickupPointID   pgtype.UUID  `json:"pickup_point_id"`
	TotalAmount     int32        `json:"total_amount"`
	PromoCodeID     pgtype.UUID  `json:"promo_code_id"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.PublicNumber,
		arg.UserID,
		arg.DeliveryType,
		arg.DeliveryAddress,
		arg.PickupPointID,
		arg.TotalAmount,
		arg.PromoCodeID,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.PublicNumber,
		&i.SearchIndex,
		&i.UserID,
		&i.Status,
		&i.DeliveryType,
		&i.DeliveryAddress,
		&i.PickupPointID,
		&i.PromoCodeID,
		&i.TotalAmount,
		&i.DiscountAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :exec
INSERT INTO order_items (order_id, sku_id, quantity, price_at_purchase)
VALUES ($1, $2, $3, $4)
`

type CreateOrderItemParams struct {
	OrderID         uuid.UUID `json:"order_id"`
	SkuID           uuid.UUID `json:"sku_id"`
	Quantity        int32     `json:"quantity"`
	PriceAtPurchase int32     `json:"price_at_purchase"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error {
	_, err := q.db.Exec(ctx, createOrderItem,
		arg.OrderID,
		arg.SkuID,
		arg.Quantity,
		arg.PriceAtPurchase,
	)
	return err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (name, description, image_url)
VALUES ($1, $2, $3)
RETURNING id, category_id, name, description, deleted_at, created_at, updated_at, image_url
`

type CreateProductParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	ImageUrl    pgtype.Text `json:"image_url"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct, arg.Name, arg.Description, arg.ImageUrl)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token, expires_at, created_at
`

type CreateSessionParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.Token, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSku = `-- name: CreateSku :one
INSERT INTO skus (product_id, sku_code, price, stock)
VALUES ($1, $2, $3, $4)
RETURNING id, product_id, sku_code, attributes, price, stock, deleted_at, created_at, updated_at
`

type CreateSkuParams struct {
	ProductID uuid.UUID `json:"product_id"`
	SkuCode   string    `json:"sku_code"`
	Price     int32     `json:"price"`
	Stock     int32     `json:"stock"`
}

func (q *Queries) CreateSku(ctx context.Context, arg CreateSkuParams) (Sku, error) {
	row := q.db.QueryRow(ctx, createSku,
		arg.ProductID,
		arg.SkuCode,
		arg.Price,
		arg.Stock,
	)
	var i Sku
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.SkuCode,
		&i.Attributes,
		&i.Price,
		&i.Stock,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, role)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, role, created_at, updated_at
`

type CreateUserParams struct {
	Email        string   `json:"email"`
	PasswordHash string   `json:"password_hash"`
	Role         UserRole `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decrementSkuStock = `-- name: DecrementSkuStock :one
UPDATE skus 
SET stock = stock - $1, updated_at = NOW()
WHERE id = $2 AND stock >= $1 AND deleted_at IS NULL
RETURNING id, product_id, sku_code, attributes, price, stock, deleted_at, created_at, updated_at
`

type DecrementSkuStockParams struct {
	Stock int32     `json:"stock"`
	ID    uuid.UUID `json:"id"`
}

// Атомарное списание остатков. Если вернет sql.ErrNoRows - значит товара не хватает (Race Condition предотвращен)
func (q *Queries) DecrementSkuStock(ctx context.Context, arg DecrementSkuStockParams) (Sku, error) {
	row := q.db.QueryRow(ctx, decrementSkuStock, arg.Stock, arg.ID)
	var i Sku
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.SkuCode,
		&i.Attributes,
		&i.Price,
		&i.Stock,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
UPDATE products
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getCartItems = `-- name: GetCartItems :many
SELECT c.quantity, s.id as sku_id, s.price, s.stock, p.name 
FROM cart_items c
JOIN skus s ON c.sku_id = s.id
JOIN products p ON s.product_id = p.id
WHERE c.user_id = $1 AND s.deleted_at IS NULL
`

type GetCartItemsRow struct {
	Quantity int32     `json:"quantity"`
	SkuID    uuid.UUID `json:"sku_id"`
	Price    int32     `json:"price"`
	Stock    int32     `json:"stock"`
	Name     string    `json:"name"`
}

func (q *Queries) GetCartItems(ctx context.Context, userID uuid.UUID) ([]GetCartItemsRow, error) {
	rows, err := q.db.Query(ctx, getCartItems, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCartItemsRow{}
	for rows.Next() {
		var i GetCartItemsRow
		if err := rows.Scan(
			&i.Quantity,
			&i.SkuID,
			&i.Price,
			&i.Stock,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, category_id, name, description, deleted_at, created_at, updated_at, image_url FROM products
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
	)
	return i, err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT s.id, s.user_id, s.token, s.expires_at, s.created_at, u.role
FROM sessions s
JOIN users u ON s.user_id = u.id
WHERE s.token = $1 AND s.expires_at > NOW()
LIMIT 1
`

type GetSessionByTokenRow struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
	Role      UserRole  `json:"role"`
}

func (q *Queries) GetSessionByToken(ctx context.Context, token string) (GetSessionByTokenRow, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, token)
	var i GetSessionByTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Role,
	)
	return i, err
}

const getSkusByProductID = `-- name: GetSkusByProductID :many
SELECT id, product_id, sku_code, attributes, price, stock, deleted_at, created_at, updated_at FROM skus
WHERE product_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSkusByProductID(ctx context.Context, productID uuid.UUID) ([]Sku, error) {
	rows, err := q.db.Query(ctx, getSkusByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sku{}
	for rows.Next() {
		var i Sku
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.SkuCode,
			&i.Attributes,
			&i.Price,
			&i.Stock,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, role, created_at, updated_at FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, email, role, created_at
FROM users
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetUsersRow struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Role      UserRole  `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) GetUsers(ctx context.Context, arg GetUsersParams) ([]GetUsersRow, error) {
	rows, err := q.db.Query(ctx, getUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsersRow{}
	for rows.Next() {
		var i GetUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, category_id, name, description, deleted_at, created_at, updated_at, image_url FROM products
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchOrders = `-- name: SearchOrders :many
SELECT id, public_number, search_index, user_id, status, delivery_type, delivery_address, pickup_point_id, promo_code_id, total_amount, discount_amount, created_at, updated_at FROM orders 
WHERE search_index = $1 
ORDER BY created_at DESC
`

// Быстрый поиск по последним 4 символам публичного номера
func (q *Queries) SearchOrders(ctx context.Context, searchIndex pgtype.Text) ([]Order, error) {
	rows, err := q.db.Query(ctx, searchOrders, searchIndex)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.PublicNumber,
			&i.SearchIndex,
			&i.UserID,
			&i.Status,
			&i.DeliveryType,
			&i.DeliveryAddress,
			&i.PickupPointID,
			&i.PromoCodeID,
			&i.TotalAmount,
			&i.DiscountAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProducts = `-- name: SearchProducts :many
SELECT DISTINCT p.id, p.category_id, p.name, p.description, p.deleted_at, p.created_at, p.updated_at, p.image_url 
FROM products p
LEFT JOIN skus s ON p.id = s.product_id AND s.deleted_at IS NULL
WHERE p.deleted_at IS NULL
  AND ($1::text = '' OR p.name ILIKE '%' || $1 || '%')
  AND ($2::int = 0 OR s.price >= $2)
  AND ($3::int = 0 OR s.price <= $3)
  AND ($4::boolean = false OR s.stock > 0)
ORDER BY p.created_at DESC
LIMIT $6::int OFFSET $5::int
`

type SearchProductsParams struct {
	SearchQuery string `json:"search_query"`
	MinPrice    int32  `json:"min_price"`
	MaxPrice    int32  `json:"max_price"`
	InStock     bool   `json:"in_stock"`
	OffsetVal   int32  `json:"offset_val"`
	LimitVal    int32  `json:"limit_val"`
}

func (q *Queries) SearchProducts(ctx context.Context, arg SearchProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, searchProducts,
		arg.SearchQuery,
		arg.MinPrice,
		arg.MaxPrice,
		arg.InStock,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = COALESCE(NULLIF($2, ''), name),
    description = COALESCE(NULLIF($3, ''), description),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, category_id, name, description, deleted_at, created_at, updated_at, image_url
`

type UpdateProductParams struct {
	ID      uuid.UUID   `json:"id"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct, arg.ID, arg.Column2, arg.Column3)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
	)
	return i, err
}

const updateProductImage = `-- name: UpdateProductImage :one
UPDATE products
SET image_url = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, category_id, name, description, deleted_at, created_at, updated_at, image_url
`

type UpdateProductImageParams struct {
	ID       uuid.UUID   `json:"id"`
	ImageUrl pgtype.Text `json:"image_url"`
}

func (q *Queries) UpdateProductImage(ctx context.Context, arg UpdateProductImageParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductImage, arg.ID, arg.ImageUrl)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
SET role = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, role, updated_at
`

type UpdateUserRoleParams struct {
	ID   uuid.UUID `json:"id"`
	Role UserRole  `json:"role"`
}

type UpdateUserRoleRow struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Role      UserRole  `json:"role"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (UpdateUserRoleRow, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role)
	var i UpdateUserRoleRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.UpdatedAt,
	)
	return i, err
}
