// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddToCart(ctx context.Context, arg AddToCartParams) error
	ClearCart(ctx context.Context, userID uuid.UUID) error
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Атомарное списание остатков. Если вернет sql.ErrNoRows - значит товара не хватает (Race Condition предотвращен)
	DecrementSkuStock(ctx context.Context, arg DecrementSkuStockParams) (Sku, error)
	GetCartItems(ctx context.Context, userID uuid.UUID) ([]GetCartItemsRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Быстрый поиск по последним 4 символам публичного номера
	SearchOrders(ctx context.Context, searchIndex pgtype.Text) ([]Order, error)
}

var _ Querier = (*Queries)(nil)
