// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repo

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addToCart = `-- name: AddToCart :exec
INSERT INTO cart_items (user_id, sku_id, quantity)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, sku_id) 
DO UPDATE SET quantity = cart_items.quantity + EXCLUDED.quantity, updated_at = NOW()
`

type AddToCartParams struct {
	UserID   uuid.UUID `json:"user_id"`
	SkuID    uuid.UUID `json:"sku_id"`
	Quantity int32     `json:"quantity"`
}

func (q *Queries) AddToCart(ctx context.Context, arg AddToCartParams) error {
	_, err := q.db.Exec(ctx, addToCart, arg.UserID, arg.SkuID, arg.Quantity)
	return err
}

const clearCart = `-- name: ClearCart :exec
DELETE FROM cart_items WHERE user_id = $1
`

func (q *Queries) ClearCart(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearCart, userID)
	return err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    public_number, user_id, delivery_type, delivery_address, 
    pickup_point_id, total_amount, promo_code_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, public_number, search_index, user_id, status, delivery_type, delivery_address, pickup_point_id, promo_code_id, total_amount, discount_amount, created_at, updated_at
`

type CreateOrderParams struct {
	PublicNumber    string         `json:"public_number"`
	UserID          uuid.UUID      `json:"user_id"`
	DeliveryType    DeliveryType   `json:"delivery_type"`
	DeliveryAddress pgtype.Text    `json:"delivery_address"`
	PickupPointID   pgtype.UUID    `json:"pickup_point_id"`
	TotalAmount     pgtype.Numeric `json:"total_amount"`
	PromoCodeID     pgtype.UUID    `json:"promo_code_id"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.PublicNumber,
		arg.UserID,
		arg.DeliveryType,
		arg.DeliveryAddress,
		arg.PickupPointID,
		arg.TotalAmount,
		arg.PromoCodeID,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.PublicNumber,
		&i.SearchIndex,
		&i.UserID,
		&i.Status,
		&i.DeliveryType,
		&i.DeliveryAddress,
		&i.PickupPointID,
		&i.PromoCodeID,
		&i.TotalAmount,
		&i.DiscountAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :exec
INSERT INTO order_items (order_id, sku_id, quantity, price_at_purchase)
VALUES ($1, $2, $3, $4)
`

type CreateOrderItemParams struct {
	OrderID         uuid.UUID      `json:"order_id"`
	SkuID           uuid.UUID      `json:"sku_id"`
	Quantity        int32          `json:"quantity"`
	PriceAtPurchase pgtype.Numeric `json:"price_at_purchase"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error {
	_, err := q.db.Exec(ctx, createOrderItem,
		arg.OrderID,
		arg.SkuID,
		arg.Quantity,
		arg.PriceAtPurchase,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, role)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, role, created_at, updated_at
`

type CreateUserParams struct {
	Email        string   `json:"email"`
	PasswordHash string   `json:"password_hash"`
	Role         UserRole `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decrementSkuStock = `-- name: DecrementSkuStock :one
UPDATE skus 
SET stock = stock - $1, updated_at = NOW()
WHERE id = $2 AND stock >= $1 AND deleted_at IS NULL
RETURNING id, product_id, sku_code, attributes, price, stock, deleted_at, created_at, updated_at
`

type DecrementSkuStockParams struct {
	Stock int32     `json:"stock"`
	ID    uuid.UUID `json:"id"`
}

// Атомарное списание остатков. Если вернет sql.ErrNoRows - значит товара не хватает (Race Condition предотвращен)
func (q *Queries) DecrementSkuStock(ctx context.Context, arg DecrementSkuStockParams) (Sku, error) {
	row := q.db.QueryRow(ctx, decrementSkuStock, arg.Stock, arg.ID)
	var i Sku
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.SkuCode,
		&i.Attributes,
		&i.Price,
		&i.Stock,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartItems = `-- name: GetCartItems :many
SELECT c.quantity, s.id as sku_id, s.price, s.stock, p.name 
FROM cart_items c
JOIN skus s ON c.sku_id = s.id
JOIN products p ON s.product_id = p.id
WHERE c.user_id = $1 AND s.deleted_at IS NULL
`

type GetCartItemsRow struct {
	Quantity int32          `json:"quantity"`
	SkuID    uuid.UUID      `json:"sku_id"`
	Price    pgtype.Numeric `json:"price"`
	Stock    int32          `json:"stock"`
	Name     string         `json:"name"`
}

func (q *Queries) GetCartItems(ctx context.Context, userID uuid.UUID) ([]GetCartItemsRow, error) {
	rows, err := q.db.Query(ctx, getCartItems, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCartItemsRow{}
	for rows.Next() {
		var i GetCartItemsRow
		if err := rows.Scan(
			&i.Quantity,
			&i.SkuID,
			&i.Price,
			&i.Stock,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, role, created_at, updated_at FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchOrders = `-- name: SearchOrders :many
SELECT id, public_number, search_index, user_id, status, delivery_type, delivery_address, pickup_point_id, promo_code_id, total_amount, discount_amount, created_at, updated_at FROM orders 
WHERE search_index = $1 
ORDER BY created_at DESC
`

// Быстрый поиск по последним 4 символам публичного номера
func (q *Queries) SearchOrders(ctx context.Context, searchIndex pgtype.Text) ([]Order, error) {
	rows, err := q.db.Query(ctx, searchOrders, searchIndex)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.PublicNumber,
			&i.SearchIndex,
			&i.UserID,
			&i.Status,
			&i.DeliveryType,
			&i.DeliveryAddress,
			&i.PickupPointID,
			&i.PromoCodeID,
			&i.TotalAmount,
			&i.DiscountAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
