// Code generated by MockGen. DO NOT EDIT.
// Source: internal/admin/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/admin/service.go -destination=internal/admin/mock/service_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	repo "github.com/XackuH-ORG/go-react-e-market/backend/internal/adapters/postgresql/sqlc"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAdminService is a mock of AdminService interface.
type MockAdminService struct {
	ctrl     *gomock.Controller
	recorder *MockAdminServiceMockRecorder
	isgomock struct{}
}

// MockAdminServiceMockRecorder is the mock recorder for MockAdminService.
type MockAdminServiceMockRecorder struct {
	mock *MockAdminService
}

// NewMockAdminService creates a new mock instance.
func NewMockAdminService(ctrl *gomock.Controller) *MockAdminService {
	mock := &MockAdminService{ctrl: ctrl}
	mock.recorder = &MockAdminServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminService) EXPECT() *MockAdminServiceMockRecorder {
	return m.recorder
}

// CreateProduct mocks base method.
func (m *MockAdminService) CreateProduct(ctx context.Context, categoryID uuid.UUID, name string, description *string) (repo.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", ctx, categoryID, name, description)
	ret0, _ := ret[0].(repo.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockAdminServiceMockRecorder) CreateProduct(ctx, categoryID, name, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockAdminService)(nil).CreateProduct), ctx, categoryID, name, description)
}

// CreateSku mocks base method.
func (m *MockAdminService) CreateSku(ctx context.Context, productID uuid.UUID, skuCode string, attributes []byte, price, stock int32) (repo.Sku, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSku", ctx, productID, skuCode, attributes, price, stock)
	ret0, _ := ret[0].(repo.Sku)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSku indicates an expected call of CreateSku.
func (mr *MockAdminServiceMockRecorder) CreateSku(ctx, productID, skuCode, attributes, price, stock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSku", reflect.TypeOf((*MockAdminService)(nil).CreateSku), ctx, productID, skuCode, attributes, price, stock)
}

// DeleteProduct mocks base method.
func (m *MockAdminService) DeleteProduct(ctx context.Context, productID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProduct", ctx, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProduct indicates an expected call of DeleteProduct.
func (mr *MockAdminServiceMockRecorder) DeleteProduct(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockAdminService)(nil).DeleteProduct), ctx, productID)
}

// DeleteSku mocks base method.
func (m *MockAdminService) DeleteSku(ctx context.Context, skuID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSku", ctx, skuID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSku indicates an expected call of DeleteSku.
func (mr *MockAdminServiceMockRecorder) DeleteSku(ctx, skuID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSku", reflect.TypeOf((*MockAdminService)(nil).DeleteSku), ctx, skuID)
}

// GetAllOrders mocks base method.
func (m *MockAdminService) GetAllOrders(ctx context.Context) ([]repo.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllOrders", ctx)
	ret0, _ := ret[0].([]repo.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllOrders indicates an expected call of GetAllOrders.
func (mr *MockAdminServiceMockRecorder) GetAllOrders(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllOrders", reflect.TypeOf((*MockAdminService)(nil).GetAllOrders), ctx)
}

// GetUsers mocks base method.
func (m *MockAdminService) GetUsers(ctx context.Context) ([]repo.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsers", ctx)
	ret0, _ := ret[0].([]repo.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsers indicates an expected call of GetUsers.
func (mr *MockAdminServiceMockRecorder) GetUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsers", reflect.TypeOf((*MockAdminService)(nil).GetUsers), ctx)
}

// SearchOrders mocks base method.
func (m *MockAdminService) SearchOrders(ctx context.Context, index string) ([]repo.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchOrders", ctx, index)
	ret0, _ := ret[0].([]repo.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchOrders indicates an expected call of SearchOrders.
func (mr *MockAdminServiceMockRecorder) SearchOrders(ctx, index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchOrders", reflect.TypeOf((*MockAdminService)(nil).SearchOrders), ctx, index)
}

// UpdateOrderStatus mocks base method.
func (m *MockAdminService) UpdateOrderStatus(ctx context.Context, orderID uuid.UUID, status repo.OrderStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatus", ctx, orderID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrderStatus indicates an expected call of UpdateOrderStatus.
func (mr *MockAdminServiceMockRecorder) UpdateOrderStatus(ctx, orderID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatus", reflect.TypeOf((*MockAdminService)(nil).UpdateOrderStatus), ctx, orderID, status)
}

// UpdateProduct mocks base method.
func (m *MockAdminService) UpdateProduct(ctx context.Context, productID, categoryID uuid.UUID, name string, description *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProduct", ctx, productID, categoryID, name, description)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProduct indicates an expected call of UpdateProduct.
func (mr *MockAdminServiceMockRecorder) UpdateProduct(ctx, productID, categoryID, name, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockAdminService)(nil).UpdateProduct), ctx, productID, categoryID, name, description)
}

// UpdateSku mocks base method.
func (m *MockAdminService) UpdateSku(ctx context.Context, skuID uuid.UUID, skuCode string, attributes []byte, price, stock int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSku", ctx, skuID, skuCode, attributes, price, stock)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSku indicates an expected call of UpdateSku.
func (mr *MockAdminServiceMockRecorder) UpdateSku(ctx, skuID, skuCode, attributes, price, stock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSku", reflect.TypeOf((*MockAdminService)(nil).UpdateSku), ctx, skuID, skuCode, attributes, price, stock)
}

// UpdateUserRole mocks base method.
func (m *MockAdminService) UpdateUserRole(ctx context.Context, userID uuid.UUID, role repo.UserRole) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserRole", ctx, userID, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserRole indicates an expected call of UpdateUserRole.
func (mr *MockAdminServiceMockRecorder) UpdateUserRole(ctx, userID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserRole", reflect.TypeOf((*MockAdminService)(nil).UpdateUserRole), ctx, userID, role)
}
