// Code generated by MockGen. DO NOT EDIT.
// Source: internal/orders/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/orders/service.go -destination=internal/orders/mock/service_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	repo "github.com/XackuH-ORG/go-react-e-market/backend/internal/adapters/postgresql/sqlc"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockOrdersService is a mock of OrdersService interface.
type MockOrdersService struct {
	ctrl     *gomock.Controller
	recorder *MockOrdersServiceMockRecorder
	isgomock struct{}
}

// MockOrdersServiceMockRecorder is the mock recorder for MockOrdersService.
type MockOrdersServiceMockRecorder struct {
	mock *MockOrdersService
}

// NewMockOrdersService creates a new mock instance.
func NewMockOrdersService(ctrl *gomock.Controller) *MockOrdersService {
	mock := &MockOrdersService{ctrl: ctrl}
	mock.recorder = &MockOrdersServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrdersService) EXPECT() *MockOrdersServiceMockRecorder {
	return m.recorder
}

// Checkout mocks base method.
func (m *MockOrdersService) Checkout(ctx context.Context, userID uuid.UUID, deliveryType repo.DeliveryType, deliveryAddress *string, pickupPointID, promoCodeID *uuid.UUID) (repo.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Checkout", ctx, userID, deliveryType, deliveryAddress, pickupPointID, promoCodeID)
	ret0, _ := ret[0].(repo.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Checkout indicates an expected call of Checkout.
func (mr *MockOrdersServiceMockRecorder) Checkout(ctx, userID, deliveryType, deliveryAddress, pickupPointID, promoCodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Checkout", reflect.TypeOf((*MockOrdersService)(nil).Checkout), ctx, userID, deliveryType, deliveryAddress, pickupPointID, promoCodeID)
}

// GetUserOrders mocks base method.
func (m *MockOrdersService) GetUserOrders(ctx context.Context, userID uuid.UUID) ([]repo.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserOrders", ctx, userID)
	ret0, _ := ret[0].([]repo.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserOrders indicates an expected call of GetUserOrders.
func (mr *MockOrdersServiceMockRecorder) GetUserOrders(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserOrders", reflect.TypeOf((*MockOrdersService)(nil).GetUserOrders), ctx, userID)
}
