// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	repo "github.com/XackuH-ORG/go-react-e-market/backend/internal/adapters/postgresql/sqlc"

	uuid "github.com/google/uuid"
)

// ProductStore is an autogenerated mock type for the ProductStore type
type ProductStore struct {
	mock.Mock
}

type ProductStore_Expecter struct {
	mock *mock.Mock
}

func (_m *ProductStore) EXPECT() *ProductStore_Expecter {
	return &ProductStore_Expecter{mock: &_m.Mock}
}

// CreateProduct provides a mock function with given fields: ctx, arg
func (_m *ProductStore) CreateProduct(ctx context.Context, arg repo.CreateProductParams) (repo.Product, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 repo.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repo.CreateProductParams) (repo.Product, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repo.CreateProductParams) repo.Product); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repo.Product)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repo.CreateProductParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProductStore_CreateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProduct'
type ProductStore_CreateProduct_Call struct {
	*mock.Call
}

// CreateProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - arg repo.CreateProductParams
func (_e *ProductStore_Expecter) CreateProduct(ctx interface{}, arg interface{}) *ProductStore_CreateProduct_Call {
	return &ProductStore_CreateProduct_Call{Call: _e.mock.On("CreateProduct", ctx, arg)}
}

func (_c *ProductStore_CreateProduct_Call) Run(run func(ctx context.Context, arg repo.CreateProductParams)) *ProductStore_CreateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repo.CreateProductParams))
	})
	return _c
}

func (_c *ProductStore_CreateProduct_Call) Return(_a0 repo.Product, _a1 error) *ProductStore_CreateProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProductStore_CreateProduct_Call) RunAndReturn(run func(context.Context, repo.CreateProductParams) (repo.Product, error)) *ProductStore_CreateProduct_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSku provides a mock function with given fields: ctx, arg
func (_m *ProductStore) CreateSku(ctx context.Context, arg repo.CreateSkuParams) (repo.Sku, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateSku")
	}

	var r0 repo.Sku
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repo.CreateSkuParams) (repo.Sku, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repo.CreateSkuParams) repo.Sku); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repo.Sku)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repo.CreateSkuParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProductStore_CreateSku_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSku'
type ProductStore_CreateSku_Call struct {
	*mock.Call
}

// CreateSku is a helper method to define mock.On call
//   - ctx context.Context
//   - arg repo.CreateSkuParams
func (_e *ProductStore_Expecter) CreateSku(ctx interface{}, arg interface{}) *ProductStore_CreateSku_Call {
	return &ProductStore_CreateSku_Call{Call: _e.mock.On("CreateSku", ctx, arg)}
}

func (_c *ProductStore_CreateSku_Call) Run(run func(ctx context.Context, arg repo.CreateSkuParams)) *ProductStore_CreateSku_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repo.CreateSkuParams))
	})
	return _c
}

func (_c *ProductStore_CreateSku_Call) Return(_a0 repo.Sku, _a1 error) *ProductStore_CreateSku_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProductStore_CreateSku_Call) RunAndReturn(run func(context.Context, repo.CreateSkuParams) (repo.Sku, error)) *ProductStore_CreateSku_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProduct provides a mock function with given fields: ctx, id
func (_m *ProductStore) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProductStore_DeleteProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProduct'
type ProductStore_DeleteProduct_Call struct {
	*mock.Call
}

// DeleteProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ProductStore_Expecter) DeleteProduct(ctx interface{}, id interface{}) *ProductStore_DeleteProduct_Call {
	return &ProductStore_DeleteProduct_Call{Call: _e.mock.On("DeleteProduct", ctx, id)}
}

func (_c *ProductStore_DeleteProduct_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ProductStore_DeleteProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ProductStore_DeleteProduct_Call) Return(_a0 error) *ProductStore_DeleteProduct_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProductStore_DeleteProduct_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *ProductStore_DeleteProduct_Call {
	_c.Call.Return(run)
	return _c
}

// GetProductWithSkus provides a mock function with given fields: ctx, id
func (_m *ProductStore) GetProductWithSkus(ctx context.Context, id uuid.UUID) ([]repo.GetProductWithSkusRow, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProductWithSkus")
	}

	var r0 []repo.GetProductWithSkusRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]repo.GetProductWithSkusRow, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []repo.GetProductWithSkusRow); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repo.GetProductWithSkusRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProductStore_GetProductWithSkus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductWithSkus'
type ProductStore_GetProductWithSkus_Call struct {
	*mock.Call
}

// GetProductWithSkus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ProductStore_Expecter) GetProductWithSkus(ctx interface{}, id interface{}) *ProductStore_GetProductWithSkus_Call {
	return &ProductStore_GetProductWithSkus_Call{Call: _e.mock.On("GetProductWithSkus", ctx, id)}
}

func (_c *ProductStore_GetProductWithSkus_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ProductStore_GetProductWithSkus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ProductStore_GetProductWithSkus_Call) Return(_a0 []repo.GetProductWithSkusRow, _a1 error) *ProductStore_GetProductWithSkus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProductStore_GetProductWithSkus_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]repo.GetProductWithSkusRow, error)) *ProductStore_GetProductWithSkus_Call {
	_c.Call.Return(run)
	return _c
}

// SearchProducts provides a mock function with given fields: ctx, arg
func (_m *ProductStore) SearchProducts(ctx context.Context, arg repo.SearchProductsParams) ([]repo.Product, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for SearchProducts")
	}

	var r0 []repo.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repo.SearchProductsParams) ([]repo.Product, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repo.SearchProductsParams) []repo.Product); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repo.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repo.SearchProductsParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProductStore_SearchProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchProducts'
type ProductStore_SearchProducts_Call struct {
	*mock.Call
}

// SearchProducts is a helper method to define mock.On call
//   - ctx context.Context
//   - arg repo.SearchProductsParams
func (_e *ProductStore_Expecter) SearchProducts(ctx interface{}, arg interface{}) *ProductStore_SearchProducts_Call {
	return &ProductStore_SearchProducts_Call{Call: _e.mock.On("SearchProducts", ctx, arg)}
}

func (_c *ProductStore_SearchProducts_Call) Run(run func(ctx context.Context, arg repo.SearchProductsParams)) *ProductStore_SearchProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repo.SearchProductsParams))
	})
	return _c
}

func (_c *ProductStore_SearchProducts_Call) Return(_a0 []repo.Product, _a1 error) *ProductStore_SearchProducts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProductStore_SearchProducts_Call) RunAndReturn(run func(context.Context, repo.SearchProductsParams) ([]repo.Product, error)) *ProductStore_SearchProducts_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProduct provides a mock function with given fields: ctx, arg
func (_m *ProductStore) UpdateProduct(ctx context.Context, arg repo.UpdateProductParams) (repo.Product, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProduct")
	}

	var r0 repo.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repo.UpdateProductParams) (repo.Product, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repo.UpdateProductParams) repo.Product); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repo.Product)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repo.UpdateProductParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProductStore_UpdateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProduct'
type ProductStore_UpdateProduct_Call struct {
	*mock.Call
}

// UpdateProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - arg repo.UpdateProductParams
func (_e *ProductStore_Expecter) UpdateProduct(ctx interface{}, arg interface{}) *ProductStore_UpdateProduct_Call {
	return &ProductStore_UpdateProduct_Call{Call: _e.mock.On("UpdateProduct", ctx, arg)}
}

func (_c *ProductStore_UpdateProduct_Call) Run(run func(ctx context.Context, arg repo.UpdateProductParams)) *ProductStore_UpdateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repo.UpdateProductParams))
	})
	return _c
}

func (_c *ProductStore_UpdateProduct_Call) Return(_a0 repo.Product, _a1 error) *ProductStore_UpdateProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProductStore_UpdateProduct_Call) RunAndReturn(run func(context.Context, repo.UpdateProductParams) (repo.Product, error)) *ProductStore_UpdateProduct_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProductImage provides a mock function with given fields: ctx, arg
func (_m *ProductStore) UpdateProductImage(ctx context.Context, arg repo.UpdateProductImageParams) (repo.Product, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProductImage")
	}

	var r0 repo.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repo.UpdateProductImageParams) (repo.Product, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repo.UpdateProductImageParams) repo.Product); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repo.Product)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repo.UpdateProductImageParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProductStore_UpdateProductImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProductImage'
type ProductStore_UpdateProductImage_Call struct {
	*mock.Call
}

// UpdateProductImage is a helper method to define mock.On call
//   - ctx context.Context
//   - arg repo.UpdateProductImageParams
func (_e *ProductStore_Expecter) UpdateProductImage(ctx interface{}, arg interface{}) *ProductStore_UpdateProductImage_Call {
	return &ProductStore_UpdateProductImage_Call{Call: _e.mock.On("UpdateProductImage", ctx, arg)}
}

func (_c *ProductStore_UpdateProductImage_Call) Run(run func(ctx context.Context, arg repo.UpdateProductImageParams)) *ProductStore_UpdateProductImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repo.UpdateProductImageParams))
	})
	return _c
}

func (_c *ProductStore_UpdateProductImage_Call) Return(_a0 repo.Product, _a1 error) *ProductStore_UpdateProductImage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProductStore_UpdateProductImage_Call) RunAndReturn(run func(context.Context, repo.UpdateProductImageParams) (repo.Product, error)) *ProductStore_UpdateProductImage_Call {
	_c.Call.Return(run)
	return _c
}

// NewProductStore creates a new instance of ProductStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductStore {
	mock := &ProductStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
