basePath: /
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: API Support
  description: API-сервер для интернет-магазина Go-React E-Market.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Go-React E-Market API
  version: "1.0"
paths:
  /health:
    get:
      description: Возвращает статус работоспособности сервера бэкенда
      produces:
      - text/plain
      responses:
        "200":
          description: all good
          schema:
            type: string
      summary: Проверка здоровья API
      tags:
      - system
securityDefinitions:
  Bearer:
    description: Введите "Bearer " и затем JWT токен в поле ввода.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
